name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~

          REPO_URL="https://github.com/mahutt/cue.git"
          BRANCH="main"
          REPO_DIR="$HOME/github-aws-ec2"

          cd "$REPO_DIR"
          git pull origin "$BRANCH"

          npm install

          echo "Starting/restarting cue API with PM2..."
          pm2 stop cue-api 2>/dev/null || true
          pm2 delete cue-app 2>/dev/null || true
          pm2 start npm --name "cue-app" -- start
          pm2 save
          pm2 startup systemd -u $USER --hp $HOME

          echo "Application deployed successfully!"
          pm2 list
          '
