name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem

          ssh -T -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} << EOF
          set -e  # Exit on any error

          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~

          REPO_URL="https://github.com/mahutt/cue.git"
          BRANCH="main"
          REPO_DIR="$HOME/github-aws-ec2"

          echo "Navigating to repository directory..."
          cd "$REPO_DIR" || { echo "Failed to navigate to $REPO_DIR"; exit 1; }

          echo "Pulling latest changes..."
          git pull origin "$BRANCH" || { echo "Git pull failed"; exit 1; }

          echo "Installing dependencies..."
          npm install || { echo "npm install failed"; exit 1; }

          # Start the application
          pm2 restart cue-app

          echo "Application deployed successfully!"
          pm2 list
          EOF
